### ISSUE TITLE
No Contact info?

### ISSUE THREAD

**Issue by MilkyHolic** [JennaScvl/Twix#2]
Hey, sorry for doing this through a github issue, you have no discord or any socials i could find. 

Concurrently there are no public wifi-streaming 3ds software that allows for local communication during streaming. 
Wireless communication is cut off as soon as any local connection is made.
For example, hosting a local room for smash bros cuts off  wifi-streaming as wireless communications are terminated. 

Point is, do you think it is possible to circumvent this? or is a hardware limitation at play here, if it is possible, its addition to your project could further cement the distance between you and other Wi-Fi-streaming 3DS software.

**Comment by JennaScvl** [comment]
Sorry for the delay, I didn't receive the email about the comment.
I can be reached on discord at .kallisti (make sure to include the .), the user name comes up as BerryBnuuy.
